name: V1 Builds

on:
  schedule:
    # At 12:15 each day. No idea what time zone this is...
    - cron:  '15 12 * * *'
  push:
  pull_request:

jobs:
  build:

    env:
      MARLIN_VERSION: ${{ matrix.branch }}
      CONFIG_NAME: ${{ matrix.machine }}

    name: ${{ matrix.machine }}-${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Allow all machines to finish building
      matrix:
        branch:
        - 2.0.5.4
        - bugfix-2.0.x
        machine:
        - V13DP_MiniRambo
        - V13DP_Ramps_MK8
        - V1CNC_Archim1
        - V1CNC_Archim1_Dual
        - V1CNC_Archim2
        - V1CNC_Archim2_Dual
        - V1CNC_MiniRambo
        - V1CNC_Rambo
        - V1CNC_Rambo_Dual
        - V1CNC_Rambo_DualLR
        - V1CNC_Ramps_Dual
        - V1CNC_Skr1p3_8825
        - V1CNC_Skr1p3_2209
        - V1CNC_Skr1p3_Dual_8825
        - V1CNC_Skr1p3_Dual_2209
        - V1CNC_Skr1p3_DualLR_8825
        - V1CNC_Skr1p3_DualLR_2209
        - V1CNC_SkrPro_2209
        - V1CNC_SkrPro_DualLR_2209
        - V1CNC_SkrPro_Dual_2209
        - V1ZXY_MiniRambo
        - V1ZXY_Ramps
        exclude:
          # Exclude specific builds from 2.0.5.4
          - branch: 2.0.5.4
            machine:
             - V1CNC_Archim1
             - V1CNC_Archim1_Dual
             - V1CNC_Archim2
             - V1CNC_Archim2_Dual

    steps:

    # Based on .github/workflows/test-builds.yml
    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/master.zip
        platformio update

    - name: Check out MarlinBuilder
      uses: actions/checkout@v2

    - name: Check out MarlinFirmware
      uses: actions/checkout@v2
      with:
        repository: MarlinFirmware/Marlin
        ref: ${{ matrix.branch }}
        path: Marlin
        clean: true
        fetch-depth: 1

    - name: Configure
      run: |
        src/core/config-for-machine ${{ matrix.machine }}

    - name: Build
      run: |
        src/core/build-for-machine

    - name: Clean Marlin for Zip
      run: |
        src/core/clean-marlin-for-zip

    - name: Save Hex
      uses: actions/upload-artifact@v2
      with:
        name: firmware-${{ matrix.machine }}-${{ matrix.branch }}
        path: firmware_*

    - name: Save Zip
      uses: actions/upload-artifact@v2
      with:
        name: MarlinFirmware-${{ matrix.machine }}-${{ matrix.branch }}
        path: Marlin_*

